llvm: Fix conflict error as following:
 Error: Transaction test error:
  file /usr/include/llvm/Config/llvm-config.h conflicts between attempted installs of lib32-llvm-dev-21.1.2-r1.core2_32 and llvm-dev-21.1.2-r1.core2_64

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>