debugedit_5.1.bbappend: Fix conflict error between debugedit-5.1-r0 and lib32-debugedit.
Error: Transaction test error:
  file /usr/bin/find-debuginfo conflicts between attempted installs of debugedit-5.1-r0.core2_64 and lib32-debugedit-5.1-r0.core2_32

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>