linux-yocto: Upgraded and fixed a build error.
 - Upgraded to 6.6.91.
 - Fix build bug with gcc15:
   build-ubinux-srpm/tmp/work-shared/ubinux-x86-64/kernel-source/include/linux/stddef.h:11:9: error: cannot use keyword 'false' as enumeration constant
   11 |         false   = 0,
      |         ^~~~~

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>