libbsd: Fix conflict error :
Error: Transaction test error:
  file /usr/include/bsd/sys/cdefs.h conflicts between attempted installs of libbsd-dev-0.12.1-r0.core2_64 and lib32-libbsd-dev-0.12.1-r0.core2_32

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>