clang: Fix conflict error when do_roofs as following:
Error: Transaction test error:
   file /usr/include/clang/Config/config.h conflicts between attempted installs of lib32-clang-dev-20.1.4-r0.core2_32 and clang-dev-20.1.4-r0.core2_64
   file /usr/include/llvm/Config/llvm-config.h conflicts between attempted installs of lib32-clang-dev-20.1.4-r0.core2_32 and clang-dev-20.1.4-r0.core2_64

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>