ls1043ardb.conf: Move to meta-ubinux to delet kernel-fitimage because it has not been supported bu poky anymore.
ERROR: ParseError at /datadrive/ubinux/workdir/ubinux-workdir/ubinux202507/yocto-ubinux/meta/classes-recipe/kernel.bbclass:183: Could not inherit file classes/kernel-fitimage.bbclass
ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>