nss-pam-ldapd: Fix build error with gcc15. This patch has not been merged yet, so added it into meta-ubinux.
build-ubinux-daily/tmp/work/armv7ahf-neon-ubinuxmllib32-linux-gnueabi/lib32-nss-pam-ldapd/0.9.12/lib32-recipe-sysroot=  -ffile-prefix-map=/datadrive/ubinux/workdir/build-dir/202506/build-ubinux-daily/tmp/work/armv7ahf-neon-ubinuxmllib32-linux-gnueabi/lib32-nss-pam-ldapd/0.9.12/recipe-sysroot-native=  -pipe -c -o pam.o ../../nss-pam-ldapd-0.9.12/nslcd/pam.c
| ../../nss-pam-ldapd-0.9.12/nslcd/cfg.c:210:38: error: 'bool' cannot be used here
|   210 | static const char *print_boolean(int bool)
|       |                                      ^~~~
| ../../nss-pam-ldapd-0.9.12/nslcd/cfg.c:210:38: note: 'bool' is a keyword with '-std=c23' onwards
| ../../nss-pam-ldapd-0.9.12/nslcd/cfg.c: In function 'print_boolean':
| ../../nss-pam-ldapd-0.9.12/nslcd/cfg.c:212:11: error: expected identifier or '(' before ')' token
|   212 |   if (bool) return "yes";
|       |           ^
| ../../nss-pam-ldapd-0.9.12/nslcd/cfg.c:212:7: error: declaration in the controlling expression must have an initializer
|   212 |   if (bool) return "yes";
|       |       ^~~~
| make[2]: *** [Makefile:501: cfg.o] Error 1

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>