openl2tp_%.bbappend: Disable ptest because li8nux-yocto6.6 doesn't support kernel-module-l2tp-ppp.
ERROR: openl2tp-1.8-r0 do_package_qa: QA Issue: openl2tp-ptest rdepends on kernel-module-l2tp-ppp, but it isn't a build dependency? [build-deps]

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>