ubinux-armv8.conf: Deleted libiodbc temporarily.
Because libiodbc has some conflicts with other OSS.

Error: Transaction test error:
  file /usr/bin/iodbc-config conflicts between attempted installs of libiodbc-3.52.15-r0.aarch64 and lib32-libiodbc-3.52.15-r0.armv7ahf_neon

Error: Transaction test error:
  file /usr/include/odbcinst.h conflicts between attempted installs of libiodbc-dev-3.52.15-r0.aarch64 and unixodbc-dev-2.3.11-r0.aarch64
  file /usr/include/sql.h conflicts between attempted installs of libiodbc-dev-3.52.15-r0.aarch64 and unixodbc-dev-2.3.11-r0.aarch64
  file /usr/include/sqlext.h conflicts between attempted installs of libiodbc-dev-3.52.15-r0.aarch64 and unixodbc-dev-2.3.11-r0.aarch64
  file /usr/include/sqltypes.h conflicts between attempted installs of libiodbc-dev-3.52.15-r0.aarch64 and unixodbc-dev-2.3.11-r0.aarch64
  file /usr/include/sqlucode.h conflicts between attempted installs of libiodbc-dev-3.52.15-r0.aarch64 and unixodbc-dev-2.3.11-r0.aarch64

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>