nghttp2: Fix do_rootfs error as the following. Because nghttp2 has dropped fetch-ocsp-response which in nghttp2-proxy package. So, deleted nghttp2-proxy from recipe.
Problem : conflicting requests

nothing provides nghttp2-proxy >= 1.66.0 needed by nghttp2-1.66.0-r0.core2_64 from base

(try to add '--skip-broken' to skip uninstallable packages)
Error: Failed to call dnf tui

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>