gjs_%.bbappend: Fix conflict error :
Running transaction test
Error: Transaction test error:
  file /usr/libexec/installed-tests/gjs/GIMarshallingTests-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0
.core2_32 and gjs-1.82.1-r0.core2_64
  file /usr/libexec/installed-tests/gjs/Regress-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0.core2_32 a
nd gjs-1.82.1-r0.core2_64
  file /usr/libexec/installed-tests/gjs/Utility-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0.core2_32 a
nd gjs-1.82.1-r0.core2_64
  file /usr/libexec/installed-tests/gjs/WarnLib-1.0.typelib conflicts between attempted installs of lib32-gjs-1.82.1-r0.core2_32 a
nd gjs-1.82.1-r0.core2_64

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>