ncurses_%.bbappend: Fix conflict error between ncurses-terminfo-base-6.5-r0.aarch64 and lib32-ncurses-terminfo-base-6.5-r0.armv7ahf_neon.
Error: Transaction test error:
  file /etc/terminfo/a/alacritty conflicts between attempted installs of lib32-ncurses-terminfo-base-6.5-r0.armv7ahf_neon and ncurses-terminfo-base-6.5-r0.aarch64

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>